language: python


git:
  depth: 99999


matrix:
  include:
    # - python: 3.3
    # - python: 3.4
    # - python: 3.5
   - python: 3.6
    # - python: 3.4.1

env:
  - APP_CONFIG_NAME=test


install:
 - pip install -r requirements.txt
 - pip install codecov
 - pip install pytest-cov


before_script:
 - "export PYTHONPATH=."

script:
  - pep8 tests/ routes/ connection/
  - flake8 routes/ connection/ tests/
  - python -m pytest --cov=./


after_success:
  - codecov

after_deploy: echo 'done deploying!'
