version: '3'
services:
 
  middleware:
    build: .
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - .:/app
    depends_on:
    - middleware_database
    networks:
    - share
  
  middleware_database:
    image: "postgres:latest"
    volumes:
     - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sg
      - POSTGRES_PASSWORD=sg
      - POSTGRES_DB=sg
    networks:
     - share
    command: gunicorn -w 1 -b :5000 app:app --reload

networks:
  share:
    driver: bridge
volumes:
  middleware_database: