version: '3'
services:

  nginx:
    build: ./nginx
    restart: always
    ports: 
    - 5000:80
    depends_on:
    - middleware
    networks:
    - share
 
  middleware:
    build: .
    restart: always
    ports:
    - "5001:5001"
    volumes:
    - .:/app
    depends_on:
    - middleware_database
    networks:
    - share
    # add gunicorn to handle internal flask threading
    command: gunicorn -w 1 -b :5001 app:app
  
  middleware_database:
    image: "postgres:latest"
    volumes:
     - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sg
      - POSTGRES_PASSWORD=sg
      - POSTGRES_DB=sg
    networks:
     - share

networks:
  share:
    driver: bridge
volumes:
  middleware_database: