#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

echo "PATCHING"
# patch openfoam input parameters
python pyfoam_patch.py
echo "PATCHED OK"

cp 0/alpha.water.orig 0/alpha.water
runApplication blockMesh
runApplication setFields
runApplication $application

#------------------------------------------------------------------------------
